# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :inetRouter => {
    :box_name => "centos/7",
    :net => [
              {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-www-net"}
            ]
  },
  :centralRouter => {
    :box_name => "centos/7",
    :net => [
              {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-www-net"},
              {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-centr-net"},
              {ip: '192.168.0.33', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "hw-centr-net"},
              {ip: '192.168.0.65', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "mgt-centr-net"},
              {ip: '192.168.254.1', adapter: 6, netmask: "255.255.255.240", virtualbox__intnet: "router-lan-net"}
            ]
  },
  :centralServer => {
    :box_name => "centos/7",
    :net => [
              {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-centr-net"},
            ]
  },
  :office1Router => {
    :box_name => "centos/7",
    :net => [
              {ip: '192.168.254.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "router-lan-net"},
              {ip: '192.168.2.1', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "dev-office1-net"},
              {ip: '192.168.2.65', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "testsrv-office1-net"},
              {ip: '192.168.2.129', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "manag-office1-net"},
              {ip: '192.168.2.193', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "hw-office1-net"}
            ]
  },
  :office1Server => {
    :box_name => "centos/7",
    :net => [
              {ip: '192.168.2.2', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "dev-office1-net"},
            ]
  },
  :office2Router => {
    :box_name => "centos/7",
    :net => [
              {ip: '192.168.254.3', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "router-lan-net"},
              {ip: '192.168.1.101', adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "dev-office2-net"},
              {ip: '192.168.1.129', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "testsrv-office2-net"},
              {ip: '192.168.1.193', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "hw-office2-net"}
            ]
  },
  :office2Server => {
    :box_name => "centos/7",
    :net => [
              {ip: '192.168.1.102', adapter: 2, netmask: "255.255.255.128", virtualbox__intnet: "dev-office2-net"},
            ]
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", ipconf
      end
    end
  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/start.yml"
  end

end
