---
- name: Copy ifcfg files for VLAN on router
  template:
    src: "{{ item }}"
    dest: /etc/sysconfig/network-scripts/{{ item | basename | regex_replace('\.j2$', '') }}
  with_fileglob:
    - "{{ role_path }}/templates/router/*.j2"
  notify:
    - Restart network
