version: '3'

services:
  mysql-server-1:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0
    ports:
      - "3301:3306"
    command: ["mysqld","--server_id=1","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]

  mysql-server-2:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0
    ports:
      - "3302:3306"
    command: ["mysqld","--server_id=2","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]

  mysql-server-3:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0
    ports:
      - "3303:3306"
    command: ["mysqld","--server_id=3","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]

  mysql-shell:
    env_file:
      - mysql-shell.env
    build: ./mysql-shell-batch
    volumes:
        - ./scripts/:/scripts/
    depends_on:
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
    environment:
      WAIT_HOSTS: mysql-server-1:3306, mysql-server-2:3306, mysql-server-3:3306
      WAIT_HOSTS_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 30

  mysql-router:
    env_file:
      - mysql-router.env
    build: ./mysql-router
    ports:
      - "6446:6446"
    depends_on:
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
    restart: on-failure
    environment:
      WAIT_HOSTS: mysql-server-1:3306, mysql-server-2:3306, mysql-server-3:3306
      WAIT_HOSTS_TIMEOUT: 600
      WAIT_AFTER_HOSTS: 90
      WAIT_SLEEP_INTERVAL: 30
