---
- name: Copy script for install pip
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp

- name: Install pip
  command: "python /tmp/get-pip.py"

- name: Install PyMySQL for mysql module
  pip:
    name: PyMySQL

- name: Get temporary root password
  shell: cat /var/log/mysqld.log | grep 'root@localhost:' | awk '{print $11}'
  register: temp_pass

- name: Set new root password
  mysql_user:
    host: "{{ item }}"
    name: root
    login_password: "{{ temp_pass }}"
    password: "{{ mysql_root_password }}"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  when: not password_is_set
