# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end

  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "10.10.10.10"
    master.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/playbooks/master.yml"
    end
  end

  config.vm.define "slave" do |slave|
    slave.vm.hostname = "slave"
    slave.vm.network "private_network", ip: "10.10.10.20"
    slave.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/playbooks/slave.yml"
    end
  end

  config.vm.define "backup" do |backup|
    backup.vm.hostname = "backup"
    backup.vm.network "private_network", ip: "10.10.10.30"
    backup.vm.provision "ansible" do |ansible|
      ansible.limit = "all"
      ansible.playbook = "provisioning/playbooks/backup.yml"
    end
  end

end
