# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define "server" do |server|
    server.vm.network "private_network", ip: "10.0.0.10"
  end

  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "10.0.0.11"
    client.vm.provision "ansible" do |ansible|
      ansible.limit = "all"
      ansible.playbook = "provisioning/start.yml"
    end
  end

end