---
- name: Install dovecot
  yum:
    name: dovecot
    state: present

- name: Copy dovecot config file
  copy:
    src: dovecot/dovecot.conf
    dest: /etc/dovecot/dovecot.conf
  notify:
    - Restart dovecot

- name: Copy dovecot conf.d files
  copy:
    src: dovecot/conf.d/
    dest: /etc/dovecot/conf.d/
  notify:
    - Restart dovecot

- name: Copy passdb file
  copy:
    src: dovecot/users
    dest: /etc/dovecot/users

- name: Check if dovecot is started and enabled
  systemd:
    name: dovecot
    state: started
    enabled: yes
