---
- name: Check if postfix is installed
  yum:
    name: postfix
    state: present

- name: Copy postfix config file
  template:
    src: postfix/main.cf.j2
    dest: /etc/postfix/main.cf
  notify:
    - Restart postfix

- name: Copy vmailbox file
  template:
    src: postfix/vmailbox.j2
    dest: /etc/postfix/vmailbox
  notify:
    - Postmap vmailbox

- name: Check if postfix is started and enabled
  systemd:
    name: postfix
    state: started
    enabled: yes
