---
- include: selinux.yml

- name: Add Nginx repo
  copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo

- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Copy default.conf
  copy:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
  notify:
    - Restart nginx

- name: Start Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
