---
- name: Check if /root/.my.cnf file exists
  stat:
    path: /root/.my.cnf
  register: root_my_cnf_stat

- name: Set root password after installing MySQL
  block:
    - name: Get temporary root password
      shell: cat /var/log/mysqld.log | grep 'root@localhost:' | awk '{print $11}'
      register: temp_pass

    # mysql_user module can't be used here, got error 1862 'Your password has expired.
    # To log in you must change it using a client that supports expired passwords.'
    - name: Set root password (using temp password to log in)
      command: >
        mysql -e "SET PASSWORD = '{{ mysql_root_password }}';"
        --connect-expired-password -uroot -p"{{ temp_pass.stdout }}"
  when: not root_my_cnf_stat.stat.exists

- name: Copy .my.cnf file into the root home folder
  template:
    src: root_my_cnf.j2
    dest: /root/.my.cnf
    mode: 0600

# Task to change root password if it exists already
- name: Set the root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
  no_log: yes
