---
- name: Install PostgreSQL repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: Install PostgreSQL client
  yum:
    name: postgresql11
    state: present

- name: Ensure EPEL repo is added
  yum:
    name: epel-release
    state: present

- name: Install barman
  yum:
    name: barman
    state: present

- name: Copy .pgpass for {{ barman_login }}
  template:
    src: barman_pgpass.j2
    dest: /var/lib/barman/.pgpass
    owner: barman
    group: barman
    mode: 0600

- name: Copy barman.conf to backup server
  template:
    src: barman.conf.j2
    dest: /etc/barman.conf

- name: Copy pg.conf to backup server
  template:
    src: pg.conf.j2
    dest: /etc/barman.d/pg.conf

- name: Check if continuous archiving is on and properly working
  become_user: barman
  shell: "barman check pg | grep 'WAL archive: FAILED' | cat"
  register: wal_archive

- name: Force PostgreSQL to switch WAL file and trigger the archiving process
  become_user: barman
  command: barman switch-wal --force --archive --archive-timeout 60 pg
  when: wal_archive.stdout != ""
