---
- name: Add EPEL repo
  yum:
    name: epel-release
    state: present

- name: Install network software
  yum:
    name: [bird, traceroute, tcpdump]
    state: present

- name: Copy bird config
  template:
    src: bird.conf.j2
    dest: /etc/bird.conf
    owner: root
    group: bird
    mode: '0640'
  notify:
    - Restart bird

- name: Start bird
  systemd:
    name: bird
    state: started
    enabled: yes
