---
- name: Install PostgreSQL and set replication
  hosts: all
  vars:
    pg_password: qwerty123
    master_host_ip: 10.10.10.10
    slave_host_ip: 10.10.10.20
    repluser_login: repluser
    repluser_password: asdf456
  roles:
    - pgsql-install
    - pgsql-replica
