# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "webserver"
  config.vm.network "private_network", ip: "10.10.10.10"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/start.yml"
  end
end
