# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define "server" do |server|
    server.vm.hostname = "nfs-server"
    server.vm.network "private_network", ip: "10.10.10.10"
    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/playbooks/nfs-server.yml"
    end
  end

  config.vm.define "client" do |client|
    client.vm.hostname = "nfs-client"
    client.vm.network "private_network", ip: "10.10.10.20"
    client.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/playbooks/nfs-client.yml"
    end
  end

end
