---
- name: Postmap vmailbox
  command: postmap /etc/postfix/vmailbox

- name: Restart postfix
  systemd:
    name: postfix
    state: restarted

- name: Restart dovecot
  systemd:
    name: dovecot
    state: restarted
