---
- name: Start and enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Redirect port 8080 to 80 of centralServer
  firewalld:
    rich_rule: rule family=ipv4 forward-port port=8080 protocol=tcp to-port=80 to-addr={{ dest_ip }}
    zone: public
    state: enabled
    permanent: yes
    immediate: yes

- name: Set masquerading to enable redirecting
  firewalld:
    zone: public
    masquerade: yes
    state: enabled
    permanent: yes
    immediate: yes
