---
- name: Copy default.conf to host
  copy:
    src: default.conf
    dest: /opt/nginx/conf.d/

- name: Install Nginx
  docker_container:
    name: nginx
    image: nginx:stable
    state: started
    restart_policy: always
    ports:
      - 80:80
      - 443:443
    volumes:
      # - /opt/nginx.conf:/etc/nginx/nginx.conf
      - /opt/nginx/conf.d/:/etc/nginx/conf.d/
      - /opt/nginx/log/:/var/log/nginx/
    networks:
      - name: "{{ network }}"
