# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define "elk" do |elk|
    elk.vm.provider "virtualbox" do |vb|
      vb.memory = 3072
      vb.cpus = 2
    end
    elk.vm.network "private_network", ip: "10.0.0.30"
    elk.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/playbooks/start_elk.yml"
    end
  end

  config.vm.define "log" do |log|
    log.vm.network "private_network", ip: "10.0.0.20"
    log.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/playbooks/start_log.yml"
    end
  end

  config.vm.define "web" do |web|
    web.vm.network "private_network", ip: "10.0.0.10"
    web.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/playbooks/start_web.yml"
    end
  end

end