---
- name: Copy database 'bet' dump to server
  copy:
    src: bet.dmp
    dest: /opt/bet.dmp

- name: Restore database 'bet' from dump
  mysql_db:
    name: bet
    state: import
    target: /opt/bet.dmp

- name: Create user for replication
  mysql_user:
    name: "{{ repl_user }}"
    password: "{{ repl_password }}"
    host: "%"
    priv: "*.*:REPLICATION SLAVE"
    state: present
  no_log: yes
