---
- name: Install Ghost
  docker_container:
    name: ghost
    image: ghost:latest
    state: started
    restart_policy: always
    ports:
      - 2368:2368
    volumes:
      - /opt/ghost/content:/var/lib/ghost/content
    env:
      url: http://{{ host_ip }}/blog
