---
- name: Install Ghost
  docker_container:
    name: ghost
    image: ghost:latest
    state: started
    restart_policy: always
    volumes:
      - /opt/ghost/content:/var/lib/ghost/content
    env:
      url: http://{{ host_ip }}/blog
    networks:
      - name: "{{ network }}"
