---
- name: Add EPEL repo
  yum:
    name: epel-release
    state: present

- name: Install pip
  yum:
    name: python-pip
    state: present

- name: Install Docker SDK for Python
  pip:
    name: docker
