---
- name: Set master for replication
  mysql_replication:
    mode: changemaster
    master_host: "{{ master_host }}"
    master_port: "{{ master_port }}"
    master_user: "{{ repl_user }}"
    master_password: "{{ repl_password }}"
    master_auto_position: yes

- name: Start slave
  mysql_replication:
    mode: startslave
