---
- name: Create directory for backup on backup server
  file:
    path: "{{ backup_path }}"
    state: directory
    owner: "{{ borg_user }}"
    group: "{{ borg_user }}"
  delegate_to: "{{ dest_host }}"

- name: Check that backup repo exists
  stat:
    path: "{{ backup_path }}/data"
  register: repo_data
  delegate_to: "{{ dest_host }}"

- name: Init Borg repo
  command: borg init -e repokey {{ borg_user }}@{{ dest_host }}:{{ backup_path }}
  environment:
    BORG_NEW_PASSPHRASE: "{{ borg_passphrase }}"
  when: not repo_data.stat.exists

- name: Copy backup script
  template:
    src: borg-etc.sh.j2
    dest: /opt/borg-etc.sh
    owner: "{{ borg_user }}"
    group: "{{ borg_user }}"
    mode: "0700"

- name: Set cron to create backup every hour
  cron:
    name: "Create backup with Borg"
    special_time: hourly
    job: "/opt/borg-etc.sh > /dev/null 2>&1"
