# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :inetRouter => {
    :box_name => "centos/7",
    :net => [
              {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "router-www-net"}
            ]
  },
  :centralRouter => {
    :box_name => "centos/7",
    :net => [
              {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "router-www-net"},
              {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-centr-net"}
            ]
  },
  :centralServer => {
    :box_name => "centos/7",
    :net => [
              {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-centr-net"}
            ]
  },
  :inetRouter2 => {
    :box_name => "centos/7",
    :fport => {guest: 8080, host: 8080},
    :net => [
              {ip: '192.168.255.3', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "router-www-net"},
            ]
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      
      boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", ipconf
      end
      
      if boxconfig.key?(:fport)
        box.vm.network "forwarded_port", boxconfig[:fport]
      end

    end
  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/start.yml"
  end

end
