---
- name: Copy ifcfg files for VLAN on host
  template:
    src: "{{ item }}"
    dest: /etc/sysconfig/network-scripts/{{ item | basename | regex_replace('\.j2$', '') }}
  with_fileglob:
    - "{{ role_path }}/templates/hosts/*.j2"
  when: vlan_number is defined
  notify:
    - Restart network

- name: Add number to ifcfg-vlan
  command:
    cmd: mv /etc/sysconfig/network-scripts/ifcfg-vlan /etc/sysconfig/network-scripts/ifcfg-vlan{{ vlan_number }}
    removes: /etc/sysconfig/network-scripts/ifcfg-vlan
  when: vlan_number is defined
