---
- name: Install Netdata
  docker_container:
    name: netdata
    image: netdata/netdata
    state: started
    restart_policy: always
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    capabilities:
      - SYS_PTRACE
    security_opts:
      - apparmor=unconfined
    env:
      VIRTUALIZATION: kvm
    networks:
      - name: "{{ network }}"
