---
- name: Install Logstash {{ logstash_version }}
  yum:
    name: logstash-{{ logstash_version }}
    state: present
    update_cache: yes

- name: Copy Logstash config files
  copy:
    src: "{{ role_path }}/files/"
    dest: /etc/logstash/conf.d/
  notify:
    - restart logstash

- name: Start Logstash
  systemd:
    name: logstash
    state: started
    enabled: yes
