---
- name: Set gateway for host on eth1
  vars:
    host: "{{inventory_hostname}}"
  ini_file:
    path: /etc/sysconfig/network-scripts/ifcfg-eth1
    section: null
    option: GATEWAY
    value: "{{ vars[host].eth1.gateway }}"
    no_extra_spaces: yes
  when: vars[host].eth1.gateway is defined
  notify:
    - Restart network
