---
- name: Config iptables on inetRouter
  iptables:
    table: nat
    action: append
    chain: POSTROUTING
    destination: '! 192.168.0.0/16'
    out_interface: eth0
    jump: MASQUERADE
  when: inventory_hostname == "inetRouter"

- name: Enable forwading on routers
  copy:
    src: forwarding.conf
    dest: /etc/sysctl.d/forwarding.conf
  when: "'Router' in inventory_hostname"
  notify:
    - Restart network

- name: Config default route
  include: default_route.yml
  when: inventory_hostname != "inetRouter"

- name: Set default gateways on host
  include: gateway.yml
  when: inventory_hostname != "inetRouter"

- name: Copy route files
  template:
    src: "{{ item }}"
    dest: /etc/sysconfig/network-scripts/{{ item | basename | regex_replace('\.j2$', '') }}
  with_fileglob:
    - "{{ role_path }}/templates/{{ inventory_hostname }}/*.j2"
  notify:
    - Restart network

# Костыль — по какой-то причине маршруты из route-eth* не подтягиваются
# после перезапуска сервиса network в хэндлере
- name: Force to restart network
  systemd:
    name: network
    state: restarted
