---
- name: Install Kibana {{ kibana_version }}
  yum:
    name: kibana-{{ kibana_version }}
    state: present
    update_cache: yes

- name: Start Kibana
  systemd:
    name: kibana
    state: started
    enabled: yes
