---
- name: Read public key on {{ source_host }}
  command: "cat /root/.ssh/id_rsa.pub"
  register: pub_key

- name: Add deploy key to authorized keys on {{ dest_host }}
  authorized_key:
    user: root
    key: "{{ pub_key.stdout }}"
  delegate_to: "{{ dest_host }}"

- name: Create SSH config
  template:
    src: config.j2
    dest: /root/.ssh/config
