# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define "one" do |one|
    one.vm.network "private_network", ip: "10.10.10.10"
    one.vm.network "private_network", ip: "10.10.20.10"
  end

  config.vm.define "two" do |two|
    two.vm.network "private_network", ip: "10.10.20.20"
    two.vm.network "private_network", ip: "10.10.30.20"
  end

  config.vm.define "three" do |three|
    three.vm.network "private_network", ip: "10.10.10.30"
    three.vm.network "private_network", ip: "10.10.30.30"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/start.yml"
  end

end
