---
- include: inet_iptables.yml
  when: inventory_hostname == "inetRouter"

- name: Copy /etc/sysconfig/network
  template:
    src: network.j2
    dest: /etc/sysconfig/network
  notify:
    - Restart network

- name: Enable forwading on routers
  copy:
    src: forwarding.conf
    dest: /etc/sysctl.d/forwarding.conf
  when: "'Router' in inventory_hostname"
  notify:
    - Restart network

- name: Config default route
  include: default_route.yml
  when: inventory_hostname != "inetRouter"

- name: Copy route files
  template:
    src: route-eth1.j2
    dest: /etc/sysconfig/network-scripts/route-eth1
  when: "'inetRouter' in inventory_hostname"
  notify:
    - Restart network

- name: Get list of interface config files
  find:
    paths: /etc/sysconfig/network-scripts
    patterns: ifcfg-eth*
  register: ifcfg_files

- name: set NM_CONTROLLED=no for all interfaces
  ini_file:
    path: "{{ item.path }}"
    section: null
    option: NM_CONTROLLED
    value: 'no'
    no_extra_spaces: yes
  with_items: "{{ ifcfg_files.files }}"
  notify:
    - Restart network

- name: Start network service
  systemd:
    name: network
    state: started
    enabled: yes

- name: Stop and disable NetworkManager
  systemd:
    name: NetworkManager
    state: stopped
    enabled: no
