# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :inetRouter => {
    :box_name => "centos/7",
    :net => [
              {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-www-net"}
            ]
  },
  :centralRouter => {
    :box_name => "centos/7",
    :net => [
              {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-www-net"},
              {ip: '192.168.254.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "router-lan-net"}
            ]
  },
  :office1Router => {
    :box_name => "centos/7",
    :net => [
              {ip: '192.168.254.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "router-lan-net"},
              {ip: '192.168.2.65', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "testsrv-office1-net"},
            ]
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", ipconf
      end
    end
  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/start.yml"
  end

end
